### ISSUE TITLE
Slimmer update function

### ISSUE THREAD

**Issue by erlandsona** [bChiquet/elm-accessors#3]
Do you have any examples of using this in conjunction with elm-return to create a slimmer update function? Or does it really require dependent types?

**Comment by bChiquet** [comment]
Hi,
First of all, dependent types are not used in this library, and I believe they are not available in Elm.
I have not used elm-return, so I don't have examples at hand.

However, from looking at elm-return examples, it seems that they use custom types heavily. While you *can* use accessors in conjunction with custom types, they won't be tremendously useful.
